### ISSUE TITLE
Please add aarch64 (linux) support

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/ncbi-datasets-cli-feedstock#260]
### Comment:

It would be great if you could also produce a conda package for linux-aarch64 - this is possible with conda-forge

**Comment by corneliusroemer** [comment]
Kicked off the migration with this PR here, given you make linux-arm builds already, it should be trivial to make them also available within conda. https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5657

**Comment by BradHolmes** [comment]
We have a strange build system here, where we build the binaries in-house, post them to https://github.com/ncbi/datasets releases, and then simply copy them into conda during the build.  So until we build it in-house, it will not be trivial to publish it here.

Let me look into this.
